# Generated by Django 5.2 on 2025-04-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
    ]
