# Generated by Django 5.2 on 2025-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='research_field',
            new_name='researchField',
        ),
    ]
