# Generated by Django 5.2 on 2025-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_rename_research_field_project_researchfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
