# Generated by Django 5.2 on 2025-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
